FROM floydhub/dl-docker:gpu
MAINTAINER Ariel Núñez <ariel@piensa.co>

ARG TENSORFLOW_VERSION=0.11.0
ARG TENSORFLOW_ARCH=gpu
ARG KERAS_VERSION=1.1.0

# Install TensorFlow
RUN pip --no-cache-dir install \
	https://storage.googleapis.com/tensorflow/linux/${TENSORFLOW_ARCH}/tensorflow-${TENSORFLOW_VERSION}-cp27-none-linux_x86_64.whl

RUN pip uninstall -y keras
# Install Keras
RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}
